### ISSUE TITLE
基于论文与项目有一些问题想请教下，方便留个联系方式吗

### ISSUE THREAD

**Issue by 3mpt** [zhangheyi-1/llmkgqas-tcm#1]
看了大语言模型融合知识图谱的问答系统研究，我最近也在做这方面的研究，有一些问题想请教一下，请留个联系方式吧！
谢谢！！

**Comment by mnyon** [comment]
> 看了大语言模型融合知识图谱的问答系统研究，我最近也在做这方面的研究，有一些问题想请教一下，请留个联系方式吧！ 谢谢！！

Agree

**Comment by zhangheyi-1** [comment]
我在readme里添加了一个联系方式，有问题可以联系我
